# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancertype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Hospuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('username', models.CharField(max_length=120, unique=True)),
                ('role', models.CharField(choices=[('Subject editor', 'subject editor'), ('Sample editor', 'sample editor'), ('Admin', 'admin')], default='subject editor', max_length=30)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosapi.Cancertype')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_id', models.CharField(max_length=120, unique=True)),
                ('subject_code', models.CharField(max_length=120)),
                ('create_date', models.DateTimeField(blank=True)),
                ('blood_type', models.CharField(choices=[('A+', 'a+'), ('A-', 'a-'), ('B+', 'b+'), ('B-', 'b-'), ('O', 'o'), ('AB+', 'ab+')], default='None', max_length=30)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosapi.Subject'),
        ),
    ]
