# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='cancer',
        ),
        migrations.AddField(
            model_name='sample',
            name='cancer',
            field=models.ManyToManyField(to='hosapi.Cancertype'),
        ),
    ]
