# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosapi', '0003_remove_hospuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospuser',
            name='password',
        ),
    ]
