# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosapi', '0004_remove_hospuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='create_date',
            field=models.DateField(blank=True),
        ),
    ]
